version: '3'

services:
  app:
    container_name: node-app
    build: .
    environment:
      - db_host=postgresql
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
  postgresql:
    container_name: postgresql
    restart: always
    image: postgres:latest
    environment:
      - POSTRGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
